album_homepage:
    path:     /
    defaults: { _controller: AlbumBundle:Album:index }

album_new:
    path:     /addAlbum
    defaults: { _controller: AlbumBundle:Album:addAlbum }

create_review:
    path:     /create_review/{id}
    defaults: { _controller: ReviewBundle:Review:addReview }
    requirements:
        id: '\d+'

view_reviews_by_album:
    path:     /view_reviews_by_album/{id}
    defaults: { _controller: ReviewBundle:Review:viewByAlbum }
    requirements:
        id: '\d+'