album_homepage:
    path:     /
    defaults: { _controller: AlbumBundle:Album:index }

add_album:
    path:     /add_album
    defaults: { _controller: AlbumBundle:Album:addAlbum }

edit_album:
    path:     /edit_album/{id}
    defaults: { _controller: AlbumBundle:Album:editAlbum }
    requirements:
        id: '\d+'

delete_album:
    path:     /delete_album/{id}
    defaults: { _controller: AlbumBundle:Album:deleteAlbum }
    requirements:
        id: '\d+'

add_review:
    path:     /add_review/{id}
    defaults: { _controller: AlbumBundle:Review:addReview }
    requirements:
        id: '\d+'

edit_review:
    path:     /edit_review/{id}
    defaults: { _controller: AlbumBundle:Review:editReview }
    requirements:
        id: '\d+'

delete_review:
    path:     /delete_review/{id}
    defaults: { _controller: AlbumBundle:Review:deleteReview }
    requirements:
        id: '\d+'

view_review:
    path:     /view_review/{id}
    defaults: { _controller: AlbumBundle:Review:viewReview }
    requirements:
        id: '\d+'

view_reviews_by_album:
    path:     /view_reviews_by_album/{id}
    defaults: { _controller: AlbumBundle:Review:viewByAlbum }
    requirements:
        id: '\d+'

view_reviews_by_user:
    path:     /view_reviews_by_user/{id}
    defaults: { _controller: AlbumBundle\Controller\UserController::viewAction }
    requirements:
        id: '\d+'

#past_event_homepage:
#    path:     /past_event_homepage
#    defaults: { _controller: AlbumBundle\Controller\Joindin:eventsAction }

#past_event_joindin:
#    path:     /past_event_joindin
#    defaults: { _controller: AlbumBundle\Controller\Joindin:eventAction }

past_talk_joindin:
    path:     /past_talk_joindin
    defaults: { _controller: AlbumBundle\Controller\Joindin:talksAction }

get_albums:
    path:     /albums
    defaults: { _controller: AlbumBundle\Controller\LastFMController::getAlbumsAction }

get_stats:
    path:     /stats
    defaults: { _controller: AlbumBundle\Controller\LastFMController::getStatsAction }

skiddle_festivals:
    path:     /festivals
    defaults: { _controller: AlbumBundle\Controller\SkiddleController:viewFestivals }

skiddle_festivals_calendar:
    path:     /calendar
    defaults: { _controller: AlbumBundle\Controller\SkiddleController:viewFestivalsCalender }

live_search:
    path:     /search
    defaults: { _controller: AlbumBundle\Controller\LastFMController::getAlbumInfoAction }
#    requirements:
#        album: '[a-z_A-Z]+'
#        artist: '[a-z_A-Z]+'