album_homepage:
    path:     /
    defaults: { _controller: AlbumBundle:Album:index }

add_album:
    path:     /addAlbum
    defaults: { _controller: AlbumBundle:Album:addAlbum }

delete_album:
    path:     /deleteAlbum
    defaults: { _controller: AlbumBundle:Album:deleteAlbum }