album_homepage:
    path:     /
    defaults: { _controller: AlbumBundle:Album:index }

add_album:
    path:     /add_album
    defaults: { _controller: AlbumBundle:Album:addAlbum }

delete_album:
    path:     /delete_album/{$id}
    defaults: { _controller: AlbumBundle:Album:deleteAlbum }
    requirements:
        id: '\d+'