albums:
  type: rest
  resource: AlbumBundle\Controller\AlbumAPIController
  name_prefix: api_albums_
  prefix: /

albums_reviews:
  type: rest
  resource: AlbumBundle\Controller\ReviewAPIController
  parent: albums
  name_prefix: api_album_reviews_

albums_tracks:
  type: rest
  resource: AlbumBundle\Controller\TrackAPIController
  parent: albums
  name_prefix: api_tracks_

users:
  type: rest
  resource: AlbumBundle\Controller\UserAPIController
  name_prefix: api_users_
  prefix: /

users_entries:
  type: rest
  resource: AlbumBundle\Controller\EntryAPIController
  name_prefix: api_entries_
  parent: users

reviews:
  type: rest
  resource: AlbumBundle\Controller\OldReviewAPIController
  name_prefix: api_reviews_
