fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

album:
    resource: "@AlbumBundle/Resources/config/routing.yml"
    prefix:   /

search:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

album_api:
    type: rest
    resource: "@AlbumBundle/Resources/config/routing_api.yml"
    prefix: /api/v1

client_creator:
    type: rest
    resource: AlbumBundle\Controller\ClientCreatorController
    prefix: /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

# > 3.0 version
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

