
# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    app.redirect_after_registration:
        class: AlbumBundle\EventListener\RedirectAfterRegistrationSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    app.security.login_form_authenticator:
        class: AlbumBundle\EventListener\LoginFormAuthenticator
        autowire: true

    app.twig_extension:
        class: SearchBundle\Twig\Extension\InstanceOfExtension
        public: false
        tags:
            - { name: twig.extension }

#    app.twig_img_extension:
#        class: AlbumBundle\Twig\Extension\FileExtension
#        public: false
#        tags:
#            - { name: twig.extension }

    SearchBundle\:
        resource: '../../src/SearchBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/SearchBundle/{Entity,Repository,Tests,Twig}'

    app.data_helper_impl:
        class: SearchBundle\Helper\DatabaseHelperImpl

    app.data_helper:
        class: SearchBundle\Command\SearchCommand
        arguments:
            - "@app.data_helper_impl" # autowire:true could have been used, but it is better to specify it


    # reusable bundle. We need to register classes as services. Hence, we need to add AlbumBundle and my reusable bundle
    AlbumBundle\:
        resource: '../../src/AlbumBundle/*'

    # pagination
    pagination_factory:
        class: AlbumBundle\Helper\PaginationFactory
        arguments: ['@router']
        public: true

    AlbumBundle\Controller\NapsterController:
        arguments:
            - '@napster.tracks'
            - '%napster_api_key%'

    AlbumBundle\Controller\LastFMController:
        arguments:
            - '@lastfm.music'
            - '%last_fm_api_key%'

    AlbumBundle\Controller\SkiddleController:
        arguments:
            - '@skiddle.events'
            - '%skiddle_api_key%'

    # Exception listener
    AlbumBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
