review_new:
    path:     /addReview
    defaults: { _controller: ReviewBundle:Review:addReview }

edit_review:
    path:     /editReview/{id}
    defaults: { _controller: ReviewBundle:Review:editReview }
    requirements:
        id: '\d+'

delete_review:
    path:     /delete_review/{id}
    defaults: { _controller: ReviewBundle:Review:deleteReview }
    requirements:
        id: '\d+'
