add_review:
    path:     /addReview/{id}
    defaults: { _controller: ReviewBundle:Review:addReview }
    requirements:
        id: '\d+'

edit_review:
    path:     /editReview/{id}
    defaults: { _controller: ReviewBundle:Review:editReview }
    requirements:
        id: '\d+'
        albumId: '\d+'

delete_review:
    path:     /delete_review/{id}
    defaults: { _controller: ReviewBundle:Review:deleteReview }
    requirements:
        id: '\d+'

view_review:
    path:     /view_review/{id}
    defaults: { _controller: ReviewBundle:Review:viewReview }
    requirements:
        id: '\d+'

view_reviews_by_album:
    path:     /view_reviews_by_album/{id}
    defaults: { _controller: ReviewBundle:Review:viewByAlbum }
    requirements:
        id: '\d+'
